export { default as getActiveGame } from './getActiveGame';
export { default as getChampionMastery } from './getChampionMastery';
export { default as getLeaguePositions } from './getLeaguePositions';
export { default as getPlatformIdByRegion } from './getPlatformIdByRegion';
export { default as getMatch } from './getMatch';
export { default as getMatchList } from './getMatchList';
export { default as getTimeline } from './getTimeline';
export { default as getSummoner } from './getSummoner';
export { default as getTrophies } from './getTrophies';
