// Account
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOGGING_IN = 'LOGGING_IN';
export const RECEIVE_TROPHY_HUNTER = 'RECEIVE_TROPHY_HUNTER';
// Encyclopedia
export const CLOSE_ENCYCLOPEDIA = 'CLOSE_ENCYCLOPEDIA';
export const OPEN_ENCYCLOPEDIA = 'OPEN_ENCYCLOPEDIA';
// Trophy Stats
export const REQUEST_TROPHY_STATS = 'REQUEST_TROPHY_STATS';
export const RECEIVE_TROPHY_STATS = 'RECEIVE_TROPHY_STATS';
export const RECEIVE_TROPHY_STATS_ERROR = 'RECEIVE_TROPHY_STATS_ERROR';
export const CLEAR_TROPHY_STATS = 'CLEAR_TROPHY_STATS';
// Participant
export const RECEIVE_PARTICIPANT_PERFORMANCE = 'RECEIVE_PARTICIPANT_PERFORMANCE';
export const REQUEST_PARTICIPANT_PERFORMANCE = 'REQUEST_PARTICIPANT_PERFORMANCE';
export const RECEIVE_PARTICIPANT_PERFORMANCE_ERROR = 'RECEIVE_PARTICIPANT_PERFORMANCE_ERROR';
export const CLEAR_PARTICIPANT_PERFORMANCE = 'CLEAR_PARTICIPANT_PERFORMANCE';
// Champion Stats
export const REQUEST_CHAMPION_STATS = 'REQUEST_CHAMPION_STATS';
export const RECEIVE_CHAMPION_STATS = 'RECEIVE_CHAMPION_STATS';
export const RECEIVE_CHAMPION_STATS_ERROR = 'RECEIVE_CHAMPION_STATS_ERROR';
export const CLEAR_CHAMPION_STATS = 'CLEAR_CHAMPION_STATS';
// Champion Matches
export const REQUEST_CHAMPION_MATCHES = 'REQUEST_CHAMPION_MATCHES';
export const RECEIVE_CHAMPION_MATCHES = 'RECEIVE_CHAMPION_MATCHES';
export const RECEIVE_CHAMPION_MATCHES_ERROR = 'RECEIVE_CHAMPION_MATCHES_ERROR';
export const CLEAR_CHAMPION_MATCHES = 'CLEAR_CHAMPION_MATCHES';
// Connection
export const RECEIVE_CONNECTION_STATUS = 'RECEIVE_CONNECTION_STATUS';
// Live-Match
export const SET_LIVE_MATCH = 'SET_LIVE_MATCH';
export const SELECT_MAP_TARGET = 'SELECT_MAP_TARGET';
export const SELECT_FIRST_TEAM_TARGET = 'SELECT_FIRST_TEAM_TARGET';
export const SELECT_SECOND_TEAM_TARGET = 'SELECT_SECOND_TEAM_TARGET';
export const SELECT_ROLE = 'SELECT_ROLE';
// Matchup matches
export const REQUEST_MATCHUP_MATCHES = 'REQUEST_MATCHUP_MATCHES';
export const RECEIVE_MATCHUP_MATCHES = 'RECEIVE_MATCHUP_MATCHES';
export const RECEIVE_MATCHUP_MATCHES_ERROR = 'RECEIVE_MATCHUP_MATCHES_ERROR';
export const CLEAR_MATCHUP_MATCHES = 'CLEAR_MATCHUP_MATCHES';
// Matchup stats
export const REQUEST_MATCHUP_STATS = 'REQUEST_MATCHUP_STATS';
export const RECEIVE_MATCHUP_STATS = 'RECEIVE_MATCHUP_STATS';
export const RECEIVE_MATCHUP_STATS_ERROR = 'RECEIVE_MATCHUP_STATS_ERROR';
export const CLEAR_MATCHUP_STATS = 'CLEAR_MATCHUP_STATS';
// Heatmap
export const RECEIVE_PARTICIPANT_HEATMAP = 'RECEIVE_PARTICIPANT_HEATMAP';
export const RECEIVE_PARTICIPANT_HEATMAP_ERROR = 'RECEIVE_PARTICIPANT_HEATMAP_ERROR';
export const REQUEST_PARTICIPANT_HEATMAP = 'REQUEST_PARTICIPANT_HEATMAP';
export const CLEAR_PARTICIPANT_HEATMAP = 'CLEAR_PARTICIPANT_HEATMAP';
// Played Together
export const RECEIVE_PLAYED_TOGETHER = 'RECEIVE_PLAYED_TOGETHER';
export const RECEIVE_PLAYED_TOGETHER_ERROR = 'RECEIVE_PLAYED_TOGETHER_ERROR';
export const REQUEST_PLAYED_TOGETHER = 'REQUEST_PLAYED_TOGETHER';
export const CLEAR_PLAYED_TOGETHER = 'CLEAR_PLAYED_TOGETHER';
// Participant matches
export const REQUEST_PARTICIPANT_MATCHES = 'REQUEST_PARTICIPANT_MATCHES';
export const RECEIVE_PARTICIPANT_MATCHES = 'RECEIVE_PARTICIPANT_MATCHES';
export const RECEIVE_PARTICIPANT_MATCHES_ERROR = 'RECEIVE_PARTICIPANT_MATCHES_ERROR';
export const CLEAR_PARTICIPANT_MATCHES = 'CLEAR_PARTICIPANT_MATCHES';
// UI States
export const SET_UI_STATE = 'SET_UI_STATE';
